# Generated by Django 5.1.6 on 2026-02-28 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_remove_dataset_description_remove_dataset_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('tgl_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('no_ktp', models.CharField(max_length=30, unique=True)),
                ('no_kk', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('kelurahan', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('dept', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('tgl_rekrut', models.DateField()),
                ('status_karyawan', models.CharField(max_length=50)),
                ('tgl_kartetap', models.DateField(blank=True, null=True)),
                ('kontrak_ke', models.IntegerField(default=0)),
                ('kontrak_berakhir', models.DateField(blank=True, null=True)),
                ('kode_gaji', models.CharField(blank=True, max_length=50)),
                ('no_rek_bank', models.CharField(blank=True, max_length=50)),
                ('kode_bank', models.CharField(blank=True, max_length=10)),
                ('nama_bank', models.CharField(blank=True, max_length=100)),
                ('status_ptkp', models.CharField(blank=True, max_length=20)),
                ('no_npwp', models.CharField(blank=True, max_length=30)),
                ('bpjs_tk', models.BooleanField(default=False)),
                ('bpjs_tk_no', models.CharField(blank=True, max_length=50)),
                ('bpjs_tk_ditanggung', models.CharField(blank=True, max_length=20)),
                ('bpjs_kes', models.BooleanField(default=False)),
                ('bpjs_kes_no', models.CharField(blank=True, max_length=50)),
                ('bpjs_kes_ditanggung', models.CharField(blank=True, max_length=20)),
                ('status_kerja', models.CharField(max_length=20)),
                ('tgl_out', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nik'],
                'indexes': [models.Index(fields=['nik'], name='hr_employee_nik_e7d13e_idx'), models.Index(fields=['no_ktp'], name='hr_employee_no_ktp_a52bef_idx'), models.Index(fields=['dept'], name='hr_employee_dept_e095a3_idx'), models.Index(fields=['status_kerja'], name='hr_employee_status__c06b93_idx'), models.Index(fields=['tgl_rekrut'], name='hr_employee_tgl_rek_b260f0_idx')],
            },
        ),
    ]
